name: Upload test coverage to code climate
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '!*' # Do not execute on tags
    paths:
      - app-web/src/*
      - app-web/journeyRegistry/*.json
      - app-web/topicRegistry/*.json
      - app-web/__tests__/*
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macOS-latest ]
        node: [ '12', '10' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run build
    - run: npm run test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install
    - run: npm run build
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: 3512ac105b5e332e8450e1c0c4003a78d07f3c52ab7520d1b0b6fac233996730
      with:
        coverageCommand: yarn coverage